### ISSUE TITLE
Issues regarding the programs

### ISSUE THREAD

**Issue by ashu96902** [ashu96902/Hacktoberfest--2021#1]
Isuues regarding reverse an array

**Comment by ashu96902** [comment]
go with this

**Comment by tech-hima** [comment]
Please assign this to me.

**Comment by saloni8273** [comment]
i want to do something in this

**Comment by ssrohit** [comment]
Hey is there something that I can contribute here.

**Comment by ChinmayaNayak21** [comment]
Allow me to do code
