### ISSUE TITLE
do some code

### ISSUE THREAD

**Issue by ashu96902** [ashu96902/Hacktoberfest--2021#10]

**Comment by ChinmayaNayak21** [comment]
Allow me to do some code

**Comment by das-amit** [comment]
Allow me to add some python code

**Comment by sd704** [comment]
I want to add some DSA in python. Please allow me.

**Comment by geekysharzeel** [comment]
allow me to do code

**Comment by csesec02** [comment]
allow me to add

**Comment by Tezz17** [comment]
allow me to add

**Comment by sunami09** [comment]
I want to add DSA in python. Please assign me.

**Comment by ashu96902** [comment]
> I want to add DSA in python. Please assign me.

**Comment by ashu96902** [comment]
> I want to add DSA in python. Please assign me.
assigned
